# Generated by Django 3.1.5 on 2021-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fact_icon', models.CharField(max_length=50)),
                ('fact', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
