# Generated by Django 3.1.5 on 2021-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
