# Generated by Django 3.1.5 on 2021-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
