# Generated by Django 3.1.5 on 2021-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210111_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='slug',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='web',
            name='slug',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
