# Generated by Django 3.1.5 on 2021-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210111_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
