# Generated by Django 3.1.5 on 2021-01-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title_url',
            field=models.URLField(max_length=100),
        ),
    ]
