# Generated by Django 3.1.5 on 2021-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210112_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(max_length=100)),
                ('youtube', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
                ('instagram', models.URLField(max_length=100)),
                ('linkedin', models.URLField(max_length=100)),
            ],
        ),
    ]
