# Generated by Django 3.1.5 on 2021-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210112_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DP',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
    ]
