# Generated by Django 3.1.5 on 2021-01-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210112_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
