# Generated by Django 3.1.5 on 2021-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210123_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='application',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_url',
            field=models.URLField(max_length=100),
        ),
    ]
