# Generated by Django 3.1.4 on 2021-05-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210505_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='image',
        ),
    ]
