# Generated by Django 3.1.4 on 2021-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210505_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
